config/routes.rb
ExampleStore::Application.routes.draw do
  devise_for :admins

  resources :products do
    get 'search', on: :collection
  end
  root :to => 'products#index'
  get 'products/:id/buy', to: 'products#buy'

  namespace :admin do
    resources :products
  end

end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :picture, type: String
  field :price, type: Float
  field :quantity, type: Integer

  def decrement_quantity
    self.quantity-=1
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_url, notice: 'Producto creado.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_products_url, notice: 'Producto editado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Producto eliminado.'}
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def buy
    @product = Product.find(params[:id])
    @product.decrement_quantity
    @product.save!
    respond_to do |format|
      format.html { redirect_to @product, notice: 'Producto adquirido' }
    end
  end

  def search
    @key = params[:key]
    regexp_keywords = Regexp.new(".*"+@key+".*",Regexp::IGNORECASE)
    @products = Product.any_of({name: regexp_keywords}, {description: regexp_keywords})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.haml
.row
  .col-lg-4
    .form-horizontal
      = form_for @product, url: url, :html => { role: 'form'} do |f|
        - if @product.errors.any?
          #error_explanation
            %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
            %ul
              - @product.errors.full_messages.each do |msg|
                %li= msg
        .form-group
          = f.label 'Nombre'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label 'Descripción'
          = f.text_area :description, class: 'form-control'
        .form-group
          = f.label 'Imagen'
          = f.text_field :picture, class: 'form-control'
        .form-group
          = f.label 'Precio'
          = f.text_field :price, class: 'form-control'
        .form-group
          = f.label 'Cantidad'
          = f.number_field :quantity, class: 'form-control'
        = f.submit 'Guardar', class: 'btn btn-default'
    %br
    %br

app/views/admin/products/edit.html.haml
%h1 Editar producto

= render 'form', url: admin_product_path

= link_to 'Volver', admin_products_path

app/views/admin/products/index.html.haml
-if notice
  .alert.alert-success.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    = notice

.admin-products
  %h1 Listado de productos
  %br
  %br
  %br
  %table.table.table-hover.table-striped.admin
    %tr
      %th Nombre
      %th Descripción
      %th Imagen
      %th Precio
      %th Cantidad
      %th
      %th

    - @products.each do |product|
      %tr
        %td= product.name
        %td= product.description
        %td= product.picture
        %td= product.price
        %td= product.quantity
        %td= link_to 'Editar', edit_admin_product_path(product)
        %td= link_to 'Eliminar', admin_product_url(product), :method => :delete, :data => { :confirm => 'Está seguro que desea eliminar el producto?' }

  %br

  = link_to 'Nuevo Producto', new_admin_product_path

app/views/admin/products/new.html.haml
%h1 Nuevo producto

= render 'form', url: admin_products_path

= link_to 'Volver', admin_products_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ExampleStore
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %a.navbar-brand{href: "/"} Tienda Virtual
        .navbar-collapse.collapse
          %form.navbar-form.navbar-right{role: 'form', :action => search_products_path, :method => 'get' }
            .form-group
              %input.form-control{name: 'key', placeholder: "Producto...", type: "search"}
            %button.btn.btn-success{type: "submit"}
              %span.glyphicon.glyphicon-search
      - if admin_signed_in?
        .navbar-header.navbar-right
          =link_to  "cerrar sesion admin", destroy_admin_session_path, method: :delete, class: 'navbar-link'
    .container
      .main
        = yield
      %hr.featurette-divider
      %footer
        %p.pull-right
          %a{href: "#"} Volver arriba
        %p
          © 2013 Railsgirls Popayán.

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = f.text_field :picture
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :quantity
    = f.number_field :quantity
  .actions
    = f.submit 'Save'

app/views/products/index.html.haml
%h1 Listado de productos
%br
%br
%br
.row
  - @products.each_with_index do |product, index|
    .col-lg-3.product
      = link_to image_tag("#{product.picture}", :border => 0, class: 'img-circle'), product
      %h2= product.name
      %p= number_to_currency(product.price, precision: 0)
      %p
        = link_to 'Detalle »', product, class: 'btn btn-default'

app/views/products/search.html.haml
%h1= "Búsqueda de productos por: #{@key}"
%br
%br
%br
.row
  - @products.each_with_index do |product, index|
    .col-lg-3.product
      = link_to image_tag("#{product.picture}", :border => 0, class: 'img-circle'), product
      %h2= product.name
      %p= number_to_currency(product.price, precision: 0)
      %p
        = link_to 'Detalle »', product, class: 'btn btn-default'

app/views/products/show.html.haml
-if notice
  .alert.alert-success.alert-dismissable
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    = notice

.show_product
  .row
    .col-lg-12
      %h1= @product.name
  .row
    .col-lg-4
      %img.product-image{src: "#{@product.picture}"}
    .col-lg-4
      %h3
        Producto
      %p= @product.name
      %h3
        Precio
      %p= number_to_currency(@product.price, precision: 0)
      %h3
        Descripción
      %p= @product.description
      %h3
        Disponibles
      %p= "#{@product.quantity}"
      %br
      %p
        %a.btn.btn-addcart.btn-primary{href: "#{product_url}/buy"}
          Comprar
      .col-lg-4
  .row
    .col-lg-12
      = link_to 'Volver a Inicio', products_path